### ISSUE TITLE
Inconsistent placement of ok/cancel buttons

### ISSUE THREAD

**Issue by madeso** [jonashertzman/FileDiff#22]
In browse dialog it's bottom right:
![image](https://user-images.githubusercontent.com/1352934/107641972-906cfd00-6c74-11eb-9b81-5650fab97a0d.png)

and options dialog its top-right
![image](https://user-images.githubusercontent.com/1352934/107641920-80551d80-6c74-11eb-975e-c903b5305ff8.png)

When in doubt I usually check visual studio layout and it seems to favor bottom right

**Comment by jonashertzman** [comment]
Fixed in build 21042
