### ISSUE TITLE
When changing the paths, a manual refresh is required before diff is displayed

### ISSUE THREAD

**Issue by madeso** [jonashertzman/FileDiff#25]
Using browse folder and manually changing the path only the diff is cleared.

**Expected:**
File difference to be displayed.

**Comment by jonashertzman** [comment]
This is done on purpose. If you compare A1.cs with A2.cs, and now you wish to compare B1.xml with B2.xml. If a compare is triggered on any change you would now compare B1.xml with A2.cs which does not make any sense.
