### ISSUE TITLE
Commandline discoverability

### ISSUE THREAD

**Issue by madeso** [jonashertzman/FileDiff#26]
```
FileDiff.exe /?
FileDiff.exe --help
FileDiff.exe -h
```
Only launched FileDiff and didn't display any help information

**Expected:**
Either a messagebox like msiexec or a commandline output indicating the usage.

**Comment by jonashertzman** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/13090098/107886959-477ea800-6f03-11eb-9683-99ad00b490a1.png)
