### ISSUE TITLE
Feature request: separate set of colors for file and folder comparison

### ISSUE THREAD

**Issue by raelb** [jonashertzman/FileDiff#28]
Thanks for your project. Nicely done.

As per the title: Feature request for separate set of colors for file and folder comparison. I like to set different text colors for folder comparison, but for file comparison, background color works better.

Also, if possible add ability to copy/paste into color picker.

**Comment by jonashertzman** [comment]
Done!

**Comment by jonashertzman** [comment]
Done!

New build published.

**Comment by raelb** [comment]
Nice - Thanks
